=== TinyTapeout/tinytapeout-index/schemas/shuttle.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Tiny Tapeout Shuttle Info Schema",
  "type": "object",
  "properties": {
    "version": { "type": "integer", "minimum": 3, "maximum": 3 },
    "id": { "type": "string" },
    "name": { "type": "string" },
    "repo": { "type": "string", "format": "uri" },
    "commit": { "type": "string", "pattern": "^[0-9a-f]{40}$" },
    "projects": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "macro": { "type": "string" },
          "address": { "type": "integer" },
          "title": { "type": "string" },
          "author": { "type": "string" },
          "description": { "type": "string" },
          "clock_hz": { "type": "integer" },
          "tiles": { "type": "string", "pattern": "^[1-8]+x[12]$" },
          "analog_pins": {
            "type": "array",
            "items": { "type": "integer" }
          },
          "repo": { "type": "string", "format": "uri" },
          "commit": { "type": "string", "pattern": "^[0-9a-f]{40}|$" },
          "pinout": {
            "type": "object",
            "propertyNames": {
              "pattern": "^[a-z_]+\\[\\d+\\]$"
            },
            "additionalProperties": { "type": "string" }
          },
          "danger_level": {
            "type": "string",
            "enum": ["unknown", "safe", "medium", "high"],
            "default": "unknown",
            "description": "Indicates the safety level of the design: 'safe' = design is safe to run, 'medium' = design can damage the ASIC under certain conditions, 'high' = design will damage the ASIC, 'unknown' = safety level is unknown"
          },
          "danger_reason": {
            "type": "string",
            "description": "Explanation of why the danger level is set to 'medium' or 'high'"
          }
        },
        "required": [
          "macro",
          "address",
          "title",
          "author",
          "description",
          "clock_hz",
          "tiles",
          "analog_pins",
          "repo",
          "commit",
          "pinout"
        ]
      }
    }
  },
  "required": ["version", "id", "name", "repo", "commit", "projects"]
}

=== TinyTapeout/tinytapeout-index/index/tt04.json
{
  "version": 3,
  "id": "tt04",
  "name": "Tiny Tapeout 4",
  "repo": "https://github.com/TinyTapeout/tinytapeout-04",
  "commit": "cf48ca5946af0f2fcad9fb479c2624144048a31b",
  "projects": [
    {
      "macro": "tt_um_4_LUT_Baungarten",
      "address": 209,
      "title": "LFMPDM (Lightning Fast Matrix Programmable Design Module)",
      "author": "Emilio Baungarten",
      "description": "8xLUTs 4-input",
      "clock_hz": 0,
      "tiles": "1x1",
      "analog_pins": [],
      "repo": "https://github.com/Baungarten-CINVESTAV/tt04-submission-4-LUT",
      "commit": "8b2252cea0d1b9cacfbeea8d43b504730ee39dda",
      "pinout": {
        "ui_in[0]": "i_addr_load_data[0]",
        "ui_in[1]": "i_addr_load_data[1]",
        "ui_in[2]": "i_addr_load_data[2]",
        "ui_in[3]": "i_addr_load_data[3]",
        "ui_in[4]": "i_Data",
        "ui_in[5]": "i_config_enable",
        "ui_in[6]": "",
        "ui_in[7]": "",
        "uo_out[0]": "o_Data",
        "uo_out[1]": "",
        "uo_out[2]": "",
        "uo_out[3]": "",
        "uo_out[4]": "",
        "uo_out[5]": "",
        "uo_out[6]": "",
        "uo_out[7]": "",
        "uio[0]": "i_LUT [0]",
        "uio[1]": "i_LUT [1]",
        "uio[2]": "i_LUT [2]",
        "uio[3]": "i_LUT [3]",
        "uio[4]": "",
        "uio[5]": "",
        "uio[6]": "",
        "uio[7]": ""
      }
    },
    {
      "macro": "tt_um_ALU_NicolasOrcasitas",
      "address": 228,
      "title": "8-bit ALU",
      "author": "Nicolas Orcasitas Garcia",
      "description": "8-bit ALU with 8 operations",
      "clock_hz": 0,
      "tiles": "1x1",
      "analog_pins": [],
      "repo": "https://github.com/NicolasOrcasitas/tt04-submission-8bit-ALU",
      "commit": "a683d97a9fec413e89ec15f2a0bfbea7e699b5f6",
      "pinout": {
        "ui_in[0]": "",
        "ui_in[1]": "",
        "ui_in[2]": "",
        "ui_in[3]": "",
        "ui_in[4]": "",
        "ui_in[5]": "",
        "ui_in[6]": "",
        "ui_in[7]": "",
        "uo_out[0]": "segment a",
        "uo_out[1]": "segment b",
        "uo_out[2]": "segment c",
        "uo_out[3]": "segment d",
        "uo_out[4]": "segment e",
        "uo_out[5]": "segment f",
        "uo_out[6]": "segment g",
        "uo_out[7]": "dot",
        "uio[0]": "",
        "uio[1]": "",
        "uio[2]": "",
        "uio[3]": "",
        "uio[4]": "",
        "uio[5]": "",
        "uio[6]": "",
        "uio[7]": ""
      }
    },
    {
      "macro": "tt_um_BounceFSM_RSX92",
      "address": 327,
      "title": "Password FSM",
      "author": "Francisco Javier Rodriguez Navarrete",
      "description": "Project for the Password FSM",
      "clock_hz": 10000000,
      "tiles": "1x1",
      "analog_pins": [],
      "repo": "https://github.com/RSX92/tt04-submission-fsmlock",
      "commit": "f441858372ef3327313a2d73e37a619a3df7c9c3",
      "pinout": {
        "ui_in[0]": "iv_data[3]",
        "ui_in[1]": "iv_data[2]",
        "ui_in[2]": "iv_data[1]",
        "ui_in[3]": "iv_data[0]",
        "ui_in[4]": "N/C",
        "ui_in[5]": "N/C",
        "ui_in[6]": "i_send_data",
        "ui_in[7]": "i_CE",
        "uo_out[0]": "o_acknowledge[7]",
        "uo_out[1]": "o_acknowledge[6]",
        "uo_out[2]": "o_acknowledge[5]",
        "uo_out[3]": "o_acknowledge[4]",
        "uo_out[4]": "o_acknowledge[3]",
        "uo_out[5]": "o_acknowledge[2]",
        "uo_out[6]": "o_acknowledge[1]",
        "uo_out[7]": "o_acknowledge[0]",
        "uio[0]": "",
        "uio[1]": "",
        "uio[2]": "",
        "uio[3]": "",
        "uio[4]": "",
        "uio[5]": "",
        "uio[6]": "",
        "uio[7]": ""
      }
    },
    {
      "macro": "tt_um_CPU",
      "address": 277,
      "title": "CPU 8 bit",
      "author": "Daniel Arevalos, Patricio Carrasco, Mario Romero, Benjamin Villegas",
      "description": "Simple CPU of 8 bit",
      "clock_hz": 0,
      "tiles": "1x1",
      "analog_pins": [],
      "repo": "https://github.com/P-coryan/Risc-V-TinyTapeout04",
      "commit": "241ec3f5e2dcd3bbb0b3cf869c28374537e75458",
      "pinout": {
        "ui_in[0]": "data_in[0]",
        "ui_in[1]": "data_in[1]",
        "ui_in[2]": "data_in[2]",
        "ui_in[3]": "data_in[3]",
        "ui_in[4]": "data_in[4]",
        "ui_in[5]": "data_in[5]",
        "ui_in[6]": "data_in[6]",
        "ui_in[7]": "data_in[7]",
        "uo_out[0]": "data_out[0]",
        "uo_out[1]": "data_out[1]",
        "uo_out[2]": "data_out[2]",
        "uo_out[3]": "data_out[3]",
        "uo_out[4]": "data_out[4]",
        "uo_out[5]": "data_out[5]",
        "uo_out[6]": "data_out[6]",
        "uo_out[7]": "data_out[7]",
        "uio[0]": "write",
        "uio[1]": "address[0]",
        "uio[2]": "address[1]",
        "uio[3]": "address[2]",
        "uio[4]": "address[3]",
        "uio[5]": "address[4]",
        "uio[6]": "address[5]",
        "uio[7]": "address[6]"
      }
    },
    {
      "macro": "tt_um_FSM",
      "address": 274,
      "title": "Microrobotics FSM",
      "author": "Lucas Irribarra, Felipe Rifo",
      "description": "Simple FSM for Micro-srobots",
      "clock_hz": 10000000,
      "tiles": "1x1",
      "analog_pins": [],
      "repo": "https://github.com/FRifoM99/tt04_MicroRobotics_FSM",
      "commit": "21a310cdd2507c01e76b02b0bec67f87d02e13ab",
      "pinout": {
        "ui_in[0]": "",
        "ui_in[1]": "",
        "ui_in[2]": "",
        "ui_in[3]": "",
        "ui_in[4]": "",
        "ui_in[5]": "Front sensor",
        "ui_in[6]": "Left sensor",
        "ui_in[7]": "Rigt sensor",
        "uo_out[0]": "motor B left",
        "uo_out[1]": "motor B Right",
        "uo_out[2]": "motor A Left",
        "uo_out[3]": "motor A Right",
        "uo_out[4]": "0",
        "uo_out[5]": "0",
        "uo_out[6]": "0",
        "uo_out[7]": "pwm signal",
        "uio[0]": "pwm resolution bit 0",
        "uio[1]": "pwm resolution bit 1",
        "uio[2]": "pwm resolution bit 2",
        "uio[3]": "pwm resolution bit 3",
        "uio[4]": "pwm resolution bit 4",
        "uio[5]": "pwm resolution bit 5",
        "uio[6]": "pwm resolution bit 6",
        "uio[7]": "pwm resolution bit 7"
      }
    },
    {
      "macro": "tt_um_FreqMeter_Juan_Garcial",
      "address": 337,
      "title": "frecuencimeter",
      "author": "Juan Carlos Garcia Lopez and Emilio Isaac Baungarten Leon",
      "description": "frecuencimeter",
      "clock_hz": 10000000,
      "tiles": "1x1",
      "analog_pins": [],
      "repo": "https://github.com/Juan-garcial2/tt04-submission-template",
      "commit": "5a1432f5c72ab9d5d5153db17dba97e5d4be4bea",
      "pinout": {
        "ui_in[0]": "data_in",
        "ui_in[1]": "",
        "ui_in[2]": "",
        "ui_in[3]": "",
        "ui_in[4]": "",
        "ui_in[5]": "",
        "ui_in[6]": "",
        "ui_in[7]": "",
        "uo_out[0]": "segments_",
        "uo_out[1]": "disp_select_",
        "uo_out[2]": "segment_select_",
        "uo_out[3]": "",
        "uo_out[4]": "",
        "uo_out[5]": "",
        "uo_out[6]": "",
        "uo_out[7]": "",
        "uio[0]": "",
        "uio[1]": "",
        "uio[2]": "",
        "uio[3]": "",
        "uio[4]": "",
        "uio[5]": "",
        "uio[6]": "",
        "uio[7]": ""
      }
    },
    {
      "macro": "tt_um_LEOGLM_hamming_code_top",
      "address": 256,
      "title": "(11,7) hamming code encoder and decoder with UART",
      "author": "LEOGLM",
      "description": "(11,7) hamming code encoder and decoder using UART Protocol",
      "clock_hz": 0,
      "tiles": "1x1",
      "analog_pins": [],
      "repo": "https://github.com/LEOGLM0312/tt04-submission-hamming_code",
      "commit": "7db5142563f4a9767d41da2c1f524f39346f2ae2",
      "pinout": {
        "ui_in[0]": "encoder and decoder switching",
        "ui_in[1]": "encoder_enable",
        "ui_in[2]": "decoder_input",
        "ui_in[3]": "encoder_input",
        "ui_in[4]": "encoder_input",
        "ui_in[5]": "encoder_input",
        "ui_in[6]": "encoder_input",
        "ui_in[7]": "encoder_input",
        "uo_out[0]": "state",
        "uo_out[1]": "encoder_output",
        "uo_out[2]": "decoder_output",
        "uo_out[3]": "decoder_output",
        "uo_out[4]": "decoder_output",
        "uo_out[5]": "decoder_output",
        "uo_out[6]": "decoder_output",
        "uo_out[7]": "decoder_output",
        "uio[0]": "encoder_input/decoder_output",
        "uio[1]": "encoder_input/decoder_output",
        "uio[2]": "encoder_input/decoder_output",
        "uio[3]": "encoder_input/decoder_output",
        "uio[4]": "encoder_input/decoder_output",
        "uio[5]": "encoder_input",
        "uio[6]": "",
        "uio[7]": ""
      }
    },
    {
      "macro": "tt_um_MichaelBell_nanoV",
      "address": 100,
      "title": "Risc-V Nano V",
      "author": "Michael Bell",
      "description": "RV32E bit serial processor",
      "clock_hz": 0,
      "tiles": "1x2",
      "analog_pins": [],
      "repo": "https://github.com/MichaelBell/tt04-nanoV",
      "commit": "76f850a4d73398e16c32a3e790d24bd27d845318",
      "pinout": {
        "ui_in[0]": "General purpose input 0",
        "ui_in[1]": "General purpose input 1",
        "ui_in[2]": "General purpose input 2",
        "ui_in[3]": "General purpose input 3",
        "ui_in[4]": "General purpose input 4",
        "ui_in[5]": "General purpose input 5",
        "ui_in[6]": "General purpose input 6",
        "ui_in[7]": "General purpose input 7",
        "uo_out[0]": "segment a / GP output 0",
        "uo_out[1]": "segment b / GP output 1",
        "uo_out[2]": "segment c / GP output 2",
        "uo_out[3]": "segment d / GP output 3",
        "uo_out[4]": "segment e / GP output 4",
        "uo_out[5]": "segment f / GP output 5",
        "uo_out[6]": "segment g / GP output 6",
        "uo_out[7]": "dot / GP output 7",
        "uio[0]": "SPI RAM MOSI",
        "uio[1]": "SPI RAM CSn",
        "uio[2]": "SPI RAM SCK",
        "uio[3]": "SPI RAM MISO",
        "uio[4]": "UART RX",
        "uio[5]": "UART TX",
